{"name": "Login with valid credentials", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 109\nCurrent browser version is 111.0.5563.64 with binary path /usr/bin/google-chrome\nStacktrace:\n#0 0x561d97e61303 <unknown>\n#1 0x561d97c35d37 <unknown>\n#2 0x561d97c62a54 <unknown>\n#3 0x561d97c5d80e <unknown>\n#4 0x561d97c5a330 <unknown>\n#5 0x561d97c9b4a6 <unknown>\n#6 0x561d97c92753 <unknown>\n#7 0x561d97c65a14 <unknown>\n#8 0x561d97c66b7e <unknown>\n#9 0x561d97eb032e <unknown>\n#10 0x561d97eb3c0e <unknown>\n#11 0x561d97e96610 <unknown>\n#12 0x561d97eb4c23 <unknown>\n#13 0x561d97e88545 <unknown>\n#14 0x561d97ed56a8 <unknown>\n#15 0x561d97ed5836 <unknown>\n#16 0x561d97ef0d13 <unknown>\n#17 0x7f2018162fd4 <unknown>\n\n", "trace": "  File \"/usr/local/lib/python3.10/dist-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/usr/local/lib/python3.10/dist-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"orangehrm/pom/features/steps/loginsteps.py\", line 10, in launchBrowser\n    b.browserSetUp(context, \"chrome\")\n  File \"/usr/local/google/home/sateeshg/git-pythonselenium/orangehrm/pom/browsersetup/browseractions.py\", line 18, in browserSetUp\n    self.driver = webdriver.Chrome(\"/usr/local/google/home/sateeshg/git-pythonselenium/orangehrm/drivers/chromedriver109\")\n  File \"/usr/local/google/home/sateeshg/.local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py\", line 69, in __init__\n    super().__init__(DesiredCapabilities.CHROME['browserName'], \"goog\",\n  File \"/usr/local/google/home/sateeshg/.local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py\", line 92, in __init__\n    super().__init__(\n  File \"/usr/local/google/home/sateeshg/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 270, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/usr/local/google/home/sateeshg/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 363, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"/usr/local/google/home/sateeshg/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 428, in execute\n    self.error_handler.check_response(response)\n  File \"/usr/local/google/home/sateeshg/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given Launch the browser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 109\nCurrent browser version is 111.0.5563.64 with binary path /usr/bin/google-chrome\nStacktrace:\n#0 0x561d97e61303 <unknown>\n#1 0x561d97c35d37 <unknown>\n#2 0x561d97c62a54 <unknown>\n#3 0x561d97c5d80e <unknown>\n#4 0x561d97c5a330 <unknown>\n#5 0x561d97c9b4a6 <unknown>\n#6 0x561d97c92753 <unknown>\n#7 0x561d97c65a14 <unknown>\n#8 0x561d97c66b7e <unknown>\n#9 0x561d97eb032e <unknown>\n#10 0x561d97eb3c0e <unknown>\n#11 0x561d97e96610 <unknown>\n#12 0x561d97eb4c23 <unknown>\n#13 0x561d97e88545 <unknown>\n#14 0x561d97ed56a8 <unknown>\n#15 0x561d97ed5836 <unknown>\n#16 0x561d97ef0d13 <unknown>\n#17 0x7f2018162fd4 <unknown>\n\n", "trace": "  File \"/usr/local/lib/python3.10/dist-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/usr/local/lib/python3.10/dist-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"orangehrm/pom/features/steps/loginsteps.py\", line 10, in launchBrowser\n    b.browserSetUp(context, \"chrome\")\n  File \"/usr/local/google/home/sateeshg/git-pythonselenium/orangehrm/pom/browsersetup/browseractions.py\", line 18, in browserSetUp\n    self.driver = webdriver.Chrome(\"/usr/local/google/home/sateeshg/git-pythonselenium/orangehrm/drivers/chromedriver109\")\n  File \"/usr/local/google/home/sateeshg/.local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py\", line 69, in __init__\n    super().__init__(DesiredCapabilities.CHROME['browserName'], \"goog\",\n  File \"/usr/local/google/home/sateeshg/.local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py\", line 92, in __init__\n    super().__init__(\n  File \"/usr/local/google/home/sateeshg/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 270, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/usr/local/google/home/sateeshg/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 363, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"/usr/local/google/home/sateeshg/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 428, in execute\n    self.error_handler.check_response(response)\n  File \"/usr/local/google/home/sateeshg/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1678338684776, "stop": 1678338689295}, {"name": "When Open the URL https://www.abhibus.com/ website", "status": "skipped", "start": 1678338689296, "stop": 1678338689296}, {"name": "Then Click on the Login link", "status": "skipped", "start": 1678338689296, "stop": 1678338689296}, {"name": "And Enter a valid Mobile number", "status": "skipped", "start": 1678338689296, "stop": 1678338689296}, {"name": "And Click the Login or Signup button", "status": "skipped", "start": 1678338689296, "stop": 1678338689296}, {"name": "And OTP request message to be displayed", "status": "skipped", "start": 1678338689296, "stop": 1678338689296}, {"name": "Then Close the browser", "status": "skipped", "start": 1678338689296, "stop": 1678338689296}], "start": 1678338684775, "stop": 1678338689296, "uuid": "d69648f9-18ac-4a1e-a191-d7508ab41eca", "historyId": "f7c79187018bc51132ae9fb1af8a947f", "fullName": "validate the login feature: Login with valid credentials", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "Login"}, {"name": "tag", "value": "valid_login"}, {"name": "feature", "value": "validate the login feature"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}